# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62fc0a3c58a4aefb9c0cd5aa9ff052dda1671313d8f51cf3389d068e9c69ce7a2060f5f130c62a2243e162034bf4b20ccdda3e6b711c4566ebbc695f189de443

test:
  secret_key_base: 17221ce471f0e9b9a4d6fd45161cdaf3f82d90e4770bb3be36dbb95997879e1958da77e0ff6c33e478b3133c86664ef6d222dda5afbc3863092763577a69f0ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
